name: picrust2
owner: iuc
description: "Phylogenetic Investigation of Communities by Reconstruction of Unobserved States"
homepage_url: https://github.com/picrust/picrust2/wiki
long_description: |
      Picrust2 is a software for predicting functional abundances based only on marker gene sequences.
remote_repository_url: https://github.com/picrust/picrust2
type: unrestricted
categories:
- Metagenomics
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for the picrust2 tool suite: {{ tool_name }}"
suite:
  name: "suite_picrust2"
  description: "Phylogenetic Investigation of Communities by Reconstruction of Unobserved States"
  long_description: |
     Picrust2 is a software for predicting functional abundances based only on marker gene sequences.